services:
  torrentwatch:
    build: .
    container_name: torrentwatch
    restart: unless-stopped
    ports:
      - "5059:8000"
    env_file: ../.env
    environment:
      - TZ=Asia/Bangkok
      - DATA_DIR=/data
    volumes:
      - torrentwatch_data:/data
      - ${NAS_TORRENT_PATH}:/downloads

volumes:
  torrentwatch_data:
