version: '3.8'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: always
    expose:
      - "3000"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${NAS_VOLUME_ROOT}:${NAS_VOLUME_ROOT}:ro
    env_file: .env
    environment:
      - TZ=Asia/Bangkok
      - HOMEPAGE_VAR_VOLUME_ROOT=${NAS_VOLUME_ROOT}
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: homepage-nginx
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - TZ=Asia/Bangkok
    depends_on:
      - homepage
    networks:
      - default
      - auth_net

networks:
  default:
    driver: bridge
  auth_net:
    external: true
    name: auth_net
