#!/usr/bin/env python3
"""Render per-stack .env files from sops-encrypted vault + per-stack manifests.

This is the entry point invoked by `make secrets`. See
docs/superpowers/specs/2026-05-30-env-secrets-management-redesign-design.md
for the design.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from typing import Any, Mapping

import yaml


class RenderError(Exception):
    """Raised when a manifest references a missing vault path or violates rules."""


def compose_quote(value: Any) -> str:
    """Render a Python value as a docker-compose .env-safe string.

    Rules (matching docker-compose .env parser semantics):
      - bool/int → 'true'/'false'/str(int) unquoted
      - str with no special chars and no leading/trailing whitespace → unquoted
      - str with special chars (space, #, ", \\, $, leading/trailing whitespace)
        but no literal single quote → wrapped in single quotes
      - str containing single quote → wrapped in double quotes with \\ and "
        escaped (the only escapes compose interprets inside double quotes that
        we need here)
      - str containing newline → RenderError (multiline values not supported)
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)

    s = str(value)
    if "\n" in s or "\r" in s:
        raise RenderError(
            "value contains a newline; docker-compose .env does not support "
            "multiline values — base64-encode or split into multiple keys"
        )

    needs_quoting = (
        s != s.strip()
        or any(ch in s for ch in (" ", "#", '"', "\\", "$"))
    )
    if not needs_quoting:
        return s

    if "'" not in s:
        return f"'{s}'"

    # Has a literal single quote — use double quotes; escape \ and ".
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def lookup(vault: Mapping[str, Any], dotted_path: str) -> Any:
    """Walk a dotted path through nested dicts. Returns None if any segment is missing."""
    node: Any = vault
    for segment in dotted_path.split("."):
        if not isinstance(node, Mapping) or segment not in node:
            return None
        node = node[segment]
    return node


def render_stack(vault: Mapping[str, Any], manifest: Mapping[str, Any]) -> str:
    """Render a single stack's .env contents from a decrypted vault + manifest dict.

    Returns the file contents as a string (no I/O). Caller writes to disk.
    """
    lines: list[str] = [
        "# GENERATED by scripts/render_env.py — DO NOT EDIT",
        "# Regenerate: make secrets",
    ]

    env_map = manifest.get("env") or {}
    literals = manifest.get("literals") or {}

    seen: set[str] = set()

    for env_name, vault_path in env_map.items():
        if env_name in seen:
            raise RenderError(f"duplicate ENV name '{env_name}' in manifest")
        seen.add(env_name)
        value = lookup(vault, vault_path)
        if value is None:
            raise RenderError(
                f"manifest references missing vault path '{vault_path}' "
                f"for ENV '{env_name}'"
            )
        lines.append(f"{env_name}={compose_quote(value)}")

    for env_name, value in literals.items():
        if env_name in seen:
            raise RenderError(
                f"literal '{env_name}' collides with env mapping in same manifest"
            )
        seen.add(env_name)
        lines.append(f"{env_name}={compose_quote(value)}")

    return "\n".join(lines) + "\n"


def find_manifests(repo_root: Path) -> list[Path]:
    """Return all manifest files: every <stack>/secrets.manifest.yaml plus
    the root deploy.manifest.yaml if it exists."""
    result: list[Path] = []
    deploy = repo_root / "deploy.manifest.yaml"
    if deploy.exists():
        result.append(deploy)
    for child in sorted(repo_root.iterdir()):
        if not child.is_dir() or child.name.startswith("."):
            continue
        manifest = child / "secrets.manifest.yaml"
        if manifest.exists():
            result.append(manifest)
        # secretary/ has sub-stacks (ingest, query); recurse one level
        if child.is_dir():
            for sub in sorted(child.iterdir()):
                if not sub.is_dir():
                    continue
                sub_manifest = sub / "secrets.manifest.yaml"
                if sub_manifest.exists():
                    result.append(sub_manifest)
    return result


def output_path(manifest_path: Path) -> Path:
    """Map a manifest file to the .env file it produces."""
    if manifest_path.name == "deploy.manifest.yaml":
        return manifest_path.parent / ".env.deploy"
    return manifest_path.parent / ".env"


def load_vault(path: Path) -> dict:
    """Load a vault file. If it appears to be sops-encrypted (has a 'sops:' key
    at the top level), shell out to `sops -d`. Otherwise parse as plaintext YAML."""
    text = path.read_text()
    if "\nsops:\n" in text or text.startswith("sops:\n"):
        result = subprocess.run(
            ["sops", "-d", str(path)],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            raise RenderError(f"sops decrypt failed for {path}: {result.stderr.strip()}")
        return yaml.safe_load(result.stdout) or {}
    return yaml.safe_load(text) or {}


def load_manifest(path: Path) -> dict:
    return yaml.safe_load(path.read_text()) or {}


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(
        description="Render per-stack .env files from sops vault + manifests"
    )
    parser.add_argument(
        "--root",
        default=str(Path(__file__).resolve().parent.parent),
        help="Repo root (default: parent of scripts/)",
    )
    parser.add_argument(
        "--vault",
        default=None,
        help="Path to vault file (default: <root>/secrets/vault.sops.yaml)",
    )
    parser.add_argument(
        "--stack",
        action="append",
        default=None,
        help="Render only the named stack (may be repeated). Use the directory "
        "name (e.g. 'news-feed' or 'secretary/ingest').",
    )
    parser.add_argument(
        "--exclude",
        action="append",
        default=None,
        help="Exclude a stack from rendering (may be repeated). Use the directory "
        "name (e.g. 'scripts').",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate without writing. Exits non-zero on any error.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print rendered output to stdout instead of writing files.",
    )
    parser.add_argument(
        "--suffix",
        default="",
        help="Append this suffix to the output filename (e.g. '.new') — used "
        "for safe side-by-side rendering during migration.",
    )
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    vault_path = Path(args.vault) if args.vault else root / "secrets" / "vault.sops.yaml"

    if not vault_path.exists():
        print(f"error: vault not found at {vault_path}", file=sys.stderr)
        return 2

    try:
        vault = load_vault(vault_path)
    except RenderError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    manifests = find_manifests(root)

    def stack_label(p: Path) -> str:
        if p.name == "deploy.manifest.yaml":
            return "deploy"
        return str(p.parent.relative_to(root))

    if args.stack:
        wanted: set[str] = set(args.stack)
        manifests = [m for m in manifests if stack_label(m) in wanted]
        if not manifests:
            print(f"error: no manifests matched --stack {args.stack}", file=sys.stderr)
            return 2

    if args.exclude:
        excluded: set[str] = set(args.exclude)
        manifests = [m for m in manifests if stack_label(m) not in excluded]

    failures: list[str] = []
    for manifest_path in manifests:
        try:
            manifest = load_manifest(manifest_path)
            rendered = render_stack(vault, manifest)
        except RenderError as e:
            failures.append(f"{manifest_path}: {e}")
            continue
        if args.dry_run:
            print(f"--- {manifest_path} ---")
            print(rendered)
            continue
        if args.check:
            continue
        out_path = output_path(manifest_path)
        if args.suffix:
            out_path = out_path.with_name(out_path.name + args.suffix)
        out_path.write_text(rendered)
        try:
            rel = out_path.relative_to(root)
        except ValueError:
            rel = out_path
        print(f"  wrote {rel}")

    if failures:
        print(f"\n{len(failures)} error(s):", file=sys.stderr)
        for line in failures:
            print(f"  {line}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
