#!/usr/bin/env python3
"""Render per-stack .env files from sops-encrypted vault + per-stack manifests.

This is the entry point invoked by `make secrets`. See
docs/superpowers/specs/2026-05-30-env-secrets-management-redesign-design.md
for the design.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, Mapping


class RenderError(Exception):
    """Raised when a manifest references a missing vault path or violates rules."""


def compose_quote(value: Any) -> str:
    """Render a Python value as a docker-compose .env-safe string.

    Rules (matching docker-compose .env parser semantics):
      - bool/int → 'true'/'false'/str(int) unquoted
      - str with no special chars and no leading/trailing whitespace → unquoted
      - str with special chars (space, #, ", \\, $, leading/trailing whitespace)
        but no literal single quote → wrapped in single quotes
      - str containing single quote → wrapped in double quotes with \\ and "
        escaped (the only escapes compose interprets inside double quotes that
        we need here)
      - str containing newline → RenderError (multiline values not supported)
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)

    s = str(value)
    if "\n" in s or "\r" in s:
        raise RenderError(
            "value contains a newline; docker-compose .env does not support "
            "multiline values — base64-encode or split into multiple keys"
        )

    needs_quoting = (
        s != s.strip()
        or any(ch in s for ch in (" ", "#", '"', "\\", "$"))
    )
    if not needs_quoting:
        return s

    if "'" not in s:
        return f"'{s}'"

    # Has a literal single quote — use double quotes; escape \ and ".
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def lookup(vault: Mapping[str, Any], dotted_path: str) -> Any:
    """Walk a dotted path through nested dicts. Returns None if any segment is missing."""
    node: Any = vault
    for segment in dotted_path.split("."):
        if not isinstance(node, Mapping) or segment not in node:
            return None
        node = node[segment]
    return node


def render_stack(vault: Mapping[str, Any], manifest: Mapping[str, Any]) -> str:
    """Render a single stack's .env contents from a decrypted vault + manifest dict.

    Returns the file contents as a string (no I/O). Caller writes to disk.
    """
    lines: list[str] = [
        "# GENERATED by scripts/render_env.py — DO NOT EDIT",
        "# Regenerate: make secrets",
    ]

    env_map = manifest.get("env") or {}
    literals = manifest.get("literals") or {}

    seen: set[str] = set()

    for env_name, vault_path in env_map.items():
        if env_name in seen:
            raise RenderError(f"duplicate ENV name '{env_name}' in manifest")
        seen.add(env_name)
        value = lookup(vault, vault_path)
        if value is None:
            raise RenderError(
                f"manifest references missing vault path '{vault_path}' "
                f"for ENV '{env_name}'"
            )
        lines.append(f"{env_name}={compose_quote(value)}")

    for env_name, value in literals.items():
        if env_name in seen:
            raise RenderError(
                f"literal '{env_name}' collides with env mapping in same manifest"
            )
        seen.add(env_name)
        lines.append(f"{env_name}={compose_quote(value)}")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    # Real CLI comes in Task 8.
    print("render_env: CLI not yet implemented; see Task 8.", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
