#!/usr/bin/env python3
"""Render per-stack .env files from sops-encrypted vault + per-stack manifests.

This is the entry point invoked by `make secrets`. See
docs/superpowers/specs/2026-05-30-env-secrets-management-redesign-design.md
for the design.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, Mapping


class RenderError(Exception):
    """Raised when a manifest references a missing vault path or violates rules."""


def lookup(vault: Mapping[str, Any], dotted_path: str) -> Any:
    """Walk a dotted path through nested dicts. Returns None if any segment is missing."""
    node: Any = vault
    for segment in dotted_path.split("."):
        if not isinstance(node, Mapping) or segment not in node:
            return None
        node = node[segment]
    return node


def render_stack(vault: Mapping[str, Any], manifest: Mapping[str, Any]) -> str:
    """Render a single stack's .env contents from a decrypted vault + manifest dict.

    Returns the file contents as a string (no I/O). Caller writes to disk.
    """
    lines: list[str] = [
        "# GENERATED by scripts/render_env.py — DO NOT EDIT",
        "# Regenerate: make secrets",
    ]

    env_map = manifest.get("env") or {}
    literals = manifest.get("literals") or {}

    for env_name, vault_path in env_map.items():
        value = lookup(vault, vault_path)
        if value is None:
            raise RenderError(
                f"manifest references missing vault path '{vault_path}' "
                f"for ENV '{env_name}'"
            )
        lines.append(f"{env_name}={value}")

    for env_name, value in literals.items():
        lines.append(f"{env_name}={value}")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    # Real CLI comes in Task 8.
    print("render_env: CLI not yet implemented; see Task 8.", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
